/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

import com.bus.AccountBUS;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MSI
 */
public class AccountGUI extends javax.swing.JPanel {
    
    /**
     * Creates new form AccountGUI
     */
    AccountBUS accBUS = new AccountBUS();
    public AccountGUI() {
        initComponents();
        svgSearch.setSVGImage("com/image/search.svg", 30, 30);
        svgAdd.setSVGImage("com/image/add.svg", 30, 30);
        svgTrash.setSVGImage("com/image/trash.svg", 30, 30);
        svgTrash.setVisible(false);
        svgEdit.setSVGImage("com/image/edit.svg", 30, 30);
        svgEdit.setVisible(false);
        svgAccountlogo.setSVGImage("com/image/account.svg", 70, 70);
        //svgReload.setSVGImage("com/image/reload.svg", 40, 40);
        reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAccount = new javax.swing.JTable();
        svgEdit = new com.gui.SvgImage();
        svgTrash = new com.gui.SvgImage();
        tfSearch = new javax.swing.JTextField();
        svgSearch = new com.gui.SvgImage();
        svgAdd = new com.gui.SvgImage();
        svgAccountlogo = new com.gui.SvgImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        MainLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        MainLabel.setForeground(new java.awt.Color(255, 102, 0));
        MainLabel.setText("QUẢN LÝ TÀI KHOẢN");

        tbAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NV", "Username", "Password", "Role"
            }
        ));
        tbAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAccount);

        svgEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgEditMouseClicked(evt);
            }
        });

        svgTrash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgTrashMouseClicked(evt);
            }
        });

        svgSearch.setBackground(new java.awt.Color(255, 255, 255));
        svgSearch.setPreferredSize(new java.awt.Dimension(40, 40));
        svgSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgSearchMouseClicked(evt);
            }
        });

        svgAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgAddMouseClicked(evt);
            }
        });

        svgAccountlogo.setText("svgImage1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(svgSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                        .addComponent(svgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(svgAccountlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(MainLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(svgTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(svgAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svgAccountlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(svgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(svgAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(svgTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(svgSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void reload(){
        tbAccount.removeAll();
        tbAccount.repaint();
        accBUS.readData();
        tbAccount.setModel(accBUS.getModel());
        svgEdit.setVisible(false);
        svgTrash.setVisible(false);    
    }
    private void tbAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAccountMouseClicked
        // TODO add your handling code here:
        svgTrash.setVisible(true);  
        svgEdit.setVisible(true);
    }//GEN-LAST:event_tbAccountMouseClicked

    private void svgSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgSearchMouseClicked
        // TODO add your handling code here:
        // search by ID or role
        tbAccount.setModel(accBUS.getModel(tfSearch.getText()));
        if(AccountBUS.x) reload();
        AccountBUS.x = false;
    }//GEN-LAST:event_svgSearchMouseClicked

    private void svgAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgAddMouseClicked
        // TODO add your handling code here:
        //JFrame frADD
        AccountInfoGUI a = new AccountInfoGUI(this);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_svgAddMouseClicked

    private void svgEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgEditMouseClicked
        // TODO add your handling code here:
        String editID = accBUS.getAccount(tbAccount.getSelectedRow()).getUserId();
        String editName = accBUS.getAccount(tbAccount.getSelectedRow()).getUsername();
        String editPass = accBUS.getAccount(tbAccount.getSelectedRow()).getPassword();
        String editRole = accBUS.getAccount(tbAccount.getSelectedRow()).getRole();
        AccountInfoGUI a = new AccountInfoGUI(this,editID,editName,editPass,editRole);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_svgEditMouseClicked

    private void svgTrashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgTrashMouseClicked
        // TODO add your handling code here:
        int ques = JOptionPane.showConfirmDialog(null, "Bạn có chắc là muốn xóa không?", "Question", JOptionPane.YES_NO_OPTION);
        if(ques == JOptionPane.YES_OPTION) {
            String delID = accBUS.getAccount(tbAccount.getSelectedRow()).getUserId();
            accBUS.delete(delID);
        }
        reload();
    }//GEN-LAST:event_svgTrashMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_formMouseClicked

    public static void main(String[] args) {
        JFrame f = new JFrame();
        AccountGUI x = new AccountGUI();
        f.add(x);
        f.setSize(1280,620);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private com.gui.SvgImage svgAccountlogo;
    private com.gui.SvgImage svgAdd;
    private com.gui.SvgImage svgEdit;
    private com.gui.SvgImage svgSearch;
    private com.gui.SvgImage svgTrash;
    private javax.swing.JTable tbAccount;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
