/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.bus.AccountBUS;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class AccountInfoGUI extends javax.swing.JFrame {
    AccountBUS accBUS = new AccountBUS();
    AccountGUI ui;
    String userID;
    String username;
    String password;
    String role;
    // nếu thêm thì mode = 1, chỉnh sửa thì mode = 2 
    int mode;
    /**
     * Creates new form AccountInfoGUI
     */
    public AccountInfoGUI(AccountGUI ui) {
        this.ui = ui;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        usernameError.setVisible(false);
        passError.setVisible(false);
        roleError.setVisible(false);
        userID = accBUS.generateAccountID();
        lbID.setText(userID);
        btnConfirm.setEnabled(false);
        mode = 1;
    }
    public AccountInfoGUI(AccountGUI ui,String userid, String username,String password,String role) {
        this.ui = ui;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        usernameError.setVisible(false);
        passError.setVisible(false);
        roleError.setVisible(false);
        tfUserName.setText(username);
        tfPassword.setText(password);
        tfRole.setText(role);
        tfRole.setEditable(false);
        this.userID = userid;
        this.username = username;
        this.password = password;
        this.role = role;
        lbID.setText(userid);
        btnConfirm.setEnabled(false);
        mode = 2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfRole = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        usernameError = new javax.swing.JLabel();
        passError = new javax.swing.JLabel();
        roleError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        mainLabel.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        mainLabel.setText("Thông tin tài khoản ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Mã NV:");

        lbID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbID.setText("userID");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Tên đăng nhập:");

        tfUserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserNameFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        tfPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Chức vụ:");

        tfRole.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfRole.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfRoleFocusLost(evt);
            }
        });

        btnConfirm.setText("Xác nhận");
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
        });

        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        usernameError.setForeground(new java.awt.Color(255, 0, 0));
        usernameError.setText("Tên đăng nhập không hợp lệ");

        passError.setForeground(new java.awt.Color(255, 0, 0));
        passError.setText("Mật khẩu không hợp lệ");

        roleError.setForeground(new java.awt.Color(255, 0, 0));
        roleError.setText("Chức vụ không hợp lệ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(lbID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameError)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnConfirm)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancel))
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(tfPassword)
                                .addComponent(tfRole)
                                .addComponent(tfUserName))
                            .addComponent(passError, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleError, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbID))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(usernameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(passError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tfRole, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roleError)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusLost
        // TODO add your handling code here:
        if(!checkUsername()) {
            usernameError.setVisible(true);
            btnConfirm.setEnabled(false);
        }
        else {
            username = tfUserName.getText();
            usernameError.setVisible(false);
        }
    }//GEN-LAST:event_tfUserNameFocusLost

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
        if(!checkPassword()) {
            passError.setVisible(true);
            btnConfirm.setEnabled(false);
        }
        else {
            password = tfPassword.getText();
            passError.setVisible(false);
        }
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfRoleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRoleFocusLost
        // TODO add your handling code here:
        if(!checkRole()){
            roleError.setVisible(true);
            btnConfirm.setEnabled(false);
        }
        else {
            role = tfRole.getText();
            roleError.setVisible(false);
        }
    }//GEN-LAST:event_tfRoleFocusLost

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        if(checkUsername() && checkPassword() && checkRole()){
            usernameError.setVisible(false);
            passError.setVisible(false);
            roleError.setVisible(false);
            btnConfirm.setEnabled(true);
        }
    }//GEN-LAST:event_jPanel1MouseEntered

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
        // TODO add your handling code here:
        if(mode == 1)
        accBUS.add(userID,username,password,role);
        else if(mode == 2)
        accBUS.edit(userID,username,password,role);
        ui.reload();
        this.dispose();
    }//GEN-LAST:event_btnConfirmMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked
    
// nếu hợp lệ trả về true, không hợp lệ trả về false
    public boolean checkUsername(){
        String userName = tfUserName.getText();
        return !(userName.equals("") || userName.contains(" "));
    }
    public boolean checkPassword(){
        String password = tfPassword.getText();
        return !(password.equals("") || password.contains(" "));
    }
    public boolean checkRole(){
        String role = tfRole.getText();
        return role.equalsIgnoreCase("nhân viên") || role.equalsIgnoreCase("admin");
    }
    public static void main(String[] args) {
        
    }
   
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel passError;
    private javax.swing.JLabel roleError;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfRole;
    private javax.swing.JTextField tfUserName;
    private javax.swing.JLabel usernameError;
    // End of variables declaration//GEN-END:variables

}
