/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.bus.ImportBUS;
import com.bus.ImportDetailBUS;
import com.bus.PetProductBUS;
import com.bus.SupplierTempBUS;
import com.dao.CustomerDTO;
import com.dao.ImportDTO;
import com.dao.ImportDetailDTO;
import com.dao.ProductDTO;
import com.dao.SupplierDTO;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DUC PHU
 */
public class CreateImportUI extends javax.swing.JFrame {

    /**
     * Creates new form CreateImportUI
     */
    String empID = "";
    String empName = "";
    Long TotalImportAmount = 0L;
    int totalQuantity = 0;
    LocalDate today = LocalDate.now();
    Validator valid = new Validator();
    ArrayList<ProductDTO> addedList = new ArrayList<>();
    ArrayList<AddedImportItem> addedPanelItemList = new ArrayList<>();
    ArrayList<SupplierDTO> supplierList = new ArrayList<>();
    SupplierTempBUS supBus = new SupplierTempBUS();
    String supID = "";
    public CreateImportUI(String empID, String empName) {
        this.empID = empID;
        this.empName = empName;
        this.supplierList = supBus.supList;
        initComponents();
        svgAddBtn.setSVGImage("com/image/add.svg", 35, 35);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddTable = new javax.swing.JPanel();
        svgAddBtn = new com.gui.SvgImage();
        jButton1 = new javax.swing.JButton();
        lbEmployee = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        lbImportAmount = new javax.swing.JLabel();
        lbTotalImportQuantity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phiếu nhập mới");

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("ID");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Số lượng");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Tên");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Thành tiền");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Đơn giá nhập");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel7.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout AddTableLayout = new javax.swing.GroupLayout(AddTable);
        AddTable.setLayout(AddTableLayout);
        AddTableLayout.setHorizontalGroup(
            AddTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        AddTableLayout.setVerticalGroup(
            AddTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(AddTable);
        jScrollPane2.setPreferredSize(new Dimension(776, 411));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jScrollPane2.setPreferredSize(new Dimension(776, 411));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setPreferredSize(new Dimension(776, 411));

        svgAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgAddBtnMouseClicked(evt);
            }
        });

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEmployee.setText("Nhân viên : Nguyễn Lmao Lmao Lmao");

        lbDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDate.setText("Ngày : dd/MM/yyyy");

        lbImportAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbImportAmount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbImportAmount.setText("Tổng tiền : 0đ");

        lbTotalImportQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotalImportQuantity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTotalImportQuantity.setText("Tổng số sản phẩm nhập về : 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(svgAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbImportAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTotalImportQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(svgAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalImportQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImportAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel4.setPreferredSize(new Dimension(776, 457));
        lbEmployee.setText("Nhân viên : "+empName);
        lbDate.setText("Ngày : "+valid.toUIDate(today));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void svgAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgAddBtnMouseClicked
        // TODO add your handling code here:
//        supID = supBus.getID(cbbSupplier.getSelectedItem().toString());
        AddImportItemUI item = new AddImportItemUI(this, addedList, addedPanelItemList);
        item.setVisible(true);
    }//GEN-LAST:event_svgAddBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PetProductBUS proBus = new PetProductBUS();
        ImportBUS impBus = new ImportBUS();
        ImportDetailBUS impDetailBUS = new ImportDetailBUS();
        ImportDTO imp = new ImportDTO();
        String impID = "";
        
        if(addedPanelItemList.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Chưa có sản phẩm");
        }
        else{
            try {
                impID = impBus.generateID();
            } catch (SQLException ex) {
                Logger.getLogger(CreateImportUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            imp.setImportID(impID);

            imp.setEmployeeID(empID);
            imp.setCreatedDate(today);
            imp.setTotalAmount(TotalImportAmount);
            try {
                impBus.add(imp);
            } catch (SQLException ex) {
                Logger.getLogger(CreateImportUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Import không thành công");
            }
        
        
            for(AddedImportItem item : addedPanelItemList)
            {
                //update quantity
                proBus.updateQuantity(item.proID, +item.quantity);

                //add into import table
                ImportDetailDTO impDetailItem = new ImportDetailDTO();
                impDetailItem.setImportID(impID);
                impDetailItem.setProductID(item.proID);
                impDetailItem.setProductName(item.proName);
                impDetailItem.setImportPrice(item.importPrice);
                impDetailItem.setQuantity(item.quantity);
                impDetailItem.setAmount(item.totalAmount);
                try {
                    impDetailBUS.add(impDetailItem);
                } catch (SQLException ex) {
                    Logger.getLogger(CreateImportUI.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Import detail không thành công");
                }
            }
        
            JOptionPane.showMessageDialog(null, "nhập hàng thành công");
            ImportDetailGUI importUi = new ImportDetailGUI(imp);
            importUi.setVisible(true);
            importUi.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            importUi.setLocationRelativeTo(null);
            this.dispose();
        }
        //add into import table
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void refreshAddTable()
    {
        AddTable.removeAll();
        AddTable.revalidate();
        AddTable.repaint();
        if(addedList.isEmpty())
        {
            
        }
        else if(addedList.size() <= 10)
        {
            AddTable.setLayout(new GridLayout(10, 1));
        }
        else if( addedList.size() > 10)
        {
            AddTable.setLayout(new GridLayout(addedList.size(), 1));
        }

        for(JPanel item : addedPanelItemList)
        {
            
            AddTable.add(item);
            
        }
    }
    
    public void addImportItem(ProductDTO product)
    {
        addedList.add(product);
        AddedImportItem item = new AddedImportItem(product, this);
        addedPanelItemList.add(item);
        refreshAddTable();
        editImportTotal();
    }
    
    public void removeImportItem(ProductDTO product)
    {
        addedList.removeIf(proTemp -> proTemp.getId().equalsIgnoreCase(product.getId()));
        addedPanelItemList.removeIf(proTemp -> proTemp.proID.equalsIgnoreCase(product.getId()));
        refreshAddTable();
        editImportTotal();
    }
    
    public void editImportTotal()
    {
        TotalImportAmount = 0L;
        totalQuantity = 0;
        for(AddedImportItem item : addedPanelItemList)
        {
            TotalImportAmount += item.totalAmount;
            totalQuantity += item.quantity;
        }
        lbImportAmount.setText(valid.formatMoney(TotalImportAmount)+"đ");
        lbTotalImportQuantity.setText("Tổng số sản phẩm nhập về : "+totalQuantity);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateImportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateImportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateImportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateImportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreateImportUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbEmployee;
    private javax.swing.JLabel lbImportAmount;
    private javax.swing.JLabel lbTotalImportQuantity;
    private com.gui.SvgImage svgAddBtn;
    // End of variables declaration//GEN-END:variables
}
