/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

import com.bus.BreedBUS;
import com.bus.PetOnStoreBUS;
import com.bus.PetProductBUS;
import com.bus.PetProductTypeBUS;
import com.bus.SoldPetBUS;
import com.bus.SupplierBUS;
import com.dao.BreedDTO;
import com.dao.PetOnStoreDTO;
import com.dao.PetProductDTO;
import com.dao.PetProductTypeDTO;
import com.dao.ProductDTO;
import com.dao.SoldPetDTO;
import com.dao.SupplierDTO;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author DUC PHU
 */
public class ProductUI extends javax.swing.JPanel {

    /**
     * Creates new form ProductCom
     */
    Validator valid = new Validator();
    
    public PetOnStoreBUS POSBus = new PetOnStoreBUS();
    
    ArrayList<PetOnStoreDTO> petOnStoreFindList = new ArrayList<>();
    
    public PetProductBUS PetProBus = new PetProductBUS();
    
    ArrayList<PetProductDTO> proFindList = new ArrayList<>();
    
    public SoldPetBUS soldBus = new SoldPetBUS();

    ArrayList<SoldPetDTO> soldFindList = new ArrayList<>();
    
    
    BreedBUS breed = new BreedBUS();
    PetProductTypeBUS typeBus = new PetProductTypeBUS();
    int hgap = 5;
    int vgap = 5;
    String section = "petonstore";
    String searchOption = "all";
    public ProductUI() {
        initComponents();
        btnDateFilter.setVisible(false);
        setSize(new Dimension(1280, 620));
//        svgAdd.setSVGImage("com/image/add.svg", 32, 32);
        Table.removeAll();
        Table.revalidate();
        Table.repaint();
        refreshTable();
//        svgAdd.setIcon(null);
        svgAdd.setSVGImage("com/image/add.svg", 32, 32);
        section = "petonstore";
        loadFilter();
        lbPetOnStore.setBackground(new Color(0xA7D2CB));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavBar = new javax.swing.JPanel();
        lbPetOnStore = new javax.swing.JLabel();
        lbSoldPet = new javax.swing.JLabel();
        lbPetProduct = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        BaseTable = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JPanel();
        svgAdd = new com.gui.SvgImage();
        jLabel1 = new javax.swing.JLabel();
        cbbFilter = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        btnDateFilter = new javax.swing.JButton();

        setBackground(new java.awt.Color(167, 210, 203));
        setName(""); // NOI18N

        NavBar.setBackground(new java.awt.Color(255, 255, 255));

        lbPetOnStore.setBackground(new java.awt.Color(255, 255, 255));
        lbPetOnStore.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPetOnStore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPetOnStore.setText("Thú đang bán");
        lbPetOnStore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPetOnStore.setOpaque(true);
        lbPetOnStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPetOnStoreMouseClicked(evt);
            }
        });

        lbSoldPet.setBackground(new java.awt.Color(255, 255, 255));
        lbSoldPet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSoldPet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSoldPet.setText("Thú đã bán");
        lbSoldPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSoldPet.setOpaque(true);
        lbSoldPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSoldPetMouseClicked(evt);
            }
        });

        lbPetProduct.setBackground(new java.awt.Color(255, 255, 255));
        lbPetProduct.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPetProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPetProduct.setText("Sản phẩm cho thú");
        lbPetProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPetProduct.setOpaque(true);
        lbPetProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPetProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPetOnStore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbSoldPet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPetProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addComponent(lbPetOnStore, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSoldPet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPetProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        List<JLabel> navButtons = Arrays.asList(lbPetOnStore, lbPetProduct, lbSoldPet);

        for(JLabel navButton : navButtons)
        {
            navButton.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e){
                    for(JLabel navBtn : navButtons)
                    {
                        navBtn.setBackground(new Color(0xFFFFFF));
                    }
                    navButton.setBackground(new Color(0xA7D2CB));
                }

            });
        }

        tfSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchKeyPressed(evt);
            }
        });

        BaseTable.setBackground(new java.awt.Color(167, 210, 203));

        scrollPane.setBackground(new java.awt.Color(167, 210, 203));
        scrollPane.setBorder(null);

        Table.setBackground(new java.awt.Color(167, 210, 203));

        javax.swing.GroupLayout TableLayout = new javax.swing.GroupLayout(Table);
        Table.setLayout(TableLayout);
        TableLayout.setHorizontalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
        );
        TableLayout.setVerticalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(Table);

        javax.swing.GroupLayout BaseTableLayout = new javax.swing.GroupLayout(BaseTable);
        BaseTable.setLayout(BaseTableLayout);
        BaseTableLayout.setHorizontalGroup(
            BaseTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );
        BaseTableLayout.setVerticalGroup(
            BaseTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );

        int scrollAmount = 15;
        scrollPane.getVerticalScrollBar().setUnitIncrement(scrollAmount);

        svgAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgAddMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Bộ lọc : ");

        cbbFilter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbbFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbFilterItemStateChanged(evt);
            }
        });
        cbbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbFilterActionPerformed(evt);
            }
        });

        btnFilter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFilter.setText("Lọc");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        btnDateFilter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDateFilter.setText("Lọc theo ngày bán");
        btnDateFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(BaseTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnDateFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(svgAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(svgAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilter)
                        .addComponent(btnDateFilter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BaseTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        BaseTable.setPreferredSize(new Dimension(1080, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void svgAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgAddMouseClicked
        // TODO add your handling code here:
//        AddPetForm addForm = new AddPetForm(this);
//        addForm.setVisible(true);
        if(section.equals("petonstore"))
        {
            AddPetForm addForm = new AddPetForm(this);
            addForm.setVisible(true);
        }
        else if(section.equals("petproduct")){
            AddProductForm addForm = new AddProductForm(this);
            addForm.setVisible(true);
        }
        
    }//GEN-LAST:event_svgAddMouseClicked

    private void lbPetOnStoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPetOnStoreMouseClicked
        // TODO add your handling code here:
        Table.removeAll();
        Table.revalidate();
        Table.repaint();
        refreshTable();
//        svgAdd.setIcon(null);
        svgAdd.setSVGImage("com/image/add.svg", 32, 32);
        section = "petonstore";
        loadFilter();
        btnDateFilter.setVisible(false);
    }//GEN-LAST:event_lbPetOnStoreMouseClicked

    private void lbPetProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPetProductMouseClicked
        // TODO add your handling code here:
        
        refreshPetProList();
        svgAdd.setSVGImage("com/image/add.svg", 32, 32);
        section = "petproduct";
        loadFilter();
        btnDateFilter.setVisible(false);
    }//GEN-LAST:event_lbPetProductMouseClicked

    private void lbSoldPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSoldPetMouseClicked
        // TODO add your handling code here:
        soldPetTable();
        svgAdd.setIcon(null);
        section = "soldpet";
        loadFilter();
        btnDateFilter.setVisible(false);
    }//GEN-LAST:event_lbSoldPetMouseClicked

    private void cbbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFilterActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbbFilterActionPerformed

    private void cbbFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbFilterItemStateChanged
        // TODO add your handling code here:
//        if(!section.equals(""))
//        {
//            System.out.println(""+cbbFilter.getSelectedItem().toString());
//        }
    }//GEN-LAST:event_cbbFilterItemStateChanged

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        
        //sử dụng search option để khoang vùng
        String option = cbbFilter.getSelectedItem().toString();
        
        //thú đang bán
        if(section.equals("petonstore"))
        {
            //xóa hết dữ liệu tìm trước đó
            petOnStoreFindList.removeAll(petOnStoreFindList);
            if(option.equalsIgnoreCase("tất cả"))
            {
                refreshTable();
            }
            else
            {
                for(PetOnStoreDTO petTemp : POSBus.petList)
                {
                    if(petTemp.getBreedId().equalsIgnoreCase(breed.getID(option)))
                    {
                        petOnStoreFindList.add(petTemp);
                    }
                }
                refreshPetFindTable(petOnStoreFindList);
            }
        }
        
        //sản phẩm
        else if(section.equals("petproduct"))
        {
            Table.removeAll();
            
            //xóa hết dữ liệu tìm trước đó
            proFindList.removeAll(proFindList);
            if(option.equalsIgnoreCase("tất cả"))
            {
                refreshPetProList();
            }
            else
            {
                for(PetProductDTO proTemp : PetProBus.productList)
                {
                    if(proTemp.getCategoryID().equalsIgnoreCase(typeBus.getID(option)))
                    {
                        proFindList.add(proTemp);
                    }
                }
                refreshProductFind(proFindList);
            }
        }
        
        //thú đã bán
        else if(section.equals("soldpet"))
        {
            Table.removeAll();
            
            //xóa hết dữ liệu tìm trước đó
            soldFindList.removeAll(soldFindList);
            if(option.equalsIgnoreCase("tất cả"))
            {
                soldPetTable();
            }
            else
            {
                for(SoldPetDTO petTemp : soldBus.soldList)
                {
                    if(petTemp.getBreedId().equalsIgnoreCase(breed.getID(option)))
                    {
                        soldFindList.add(petTemp);
                    }
                }
                refreshSoldPetFind(soldFindList);
            }
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void tfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyPressed
        // TODO add your handling code here:
        
        //lấy search option để tìm
        //
        String option = cbbFilter.getSelectedItem().toString();
        String searchText = tfSearch.getText();
        if(section.equalsIgnoreCase("petonstore"))
        {
            petOnStoreFindList.removeAll(petOnStoreFindList);
            if(option.equalsIgnoreCase("tất cả"))
            {
                for(PetOnStoreDTO petTemp : POSBus.petList)
                {
                    if( ( valid.normalizeString(petTemp.getName()).toLowerCase().contains(valid.normalizeString(searchText).toLowerCase() ) || 
                        petTemp.getId().toLowerCase().contains(searchText.toLowerCase()) ) )
                    {
                        petOnStoreFindList.add(petTemp);
                    }
                }
            }
            
            else{
                String breIDTemp = breed.getID(option);
                for(PetOnStoreDTO petTemp : POSBus.petList)
                {
                    if( ( valid.normalizeString(petTemp.getName()).toLowerCase().contains(valid.normalizeString(searchText).toLowerCase()) || 
                            petTemp.getId().equalsIgnoreCase(searchText) ) && 
                            petTemp.getBreedId().equalsIgnoreCase(breIDTemp))
                    {
                        petOnStoreFindList.add(petTemp);
                    }
                }
            }

            refreshPetFindTable(petOnStoreFindList);
        }
        else if(section.equalsIgnoreCase("petproduct"))
        {
            proFindList.removeAll(proFindList);
            if(option.equalsIgnoreCase("tất cả"))
            {
                for(PetProductDTO proTemp : PetProBus.productList)
                {
                    if( valid.normalizeString(proTemp.getName()).toLowerCase().contains(valid.normalizeString(searchText).toLowerCase()) || 
                            proTemp.getId().toLowerCase().contains(searchText.toLowerCase()) )
                    {
                        proFindList.add(proTemp);
                    }
                }
            }
            
            else
            {
                String typeIDTemp = typeBus.getID(option);
                for(PetProductDTO proTemp : PetProBus.productList)
                {
                    if( ( valid.normalizeString(proTemp.getName()).toLowerCase().contains(valid.normalizeString(searchText).toLowerCase()) || 
                            proTemp.getId().toLowerCase().contains(searchText.toLowerCase()) ) && 
                            proTemp.getCategoryID().equalsIgnoreCase(typeIDTemp))
                    {
                        proFindList.add(proTemp);
                    }
                }
            }
            refreshProductFind(proFindList);
        }
        else if(section.equalsIgnoreCase("soldpet"))
        {
            soldFindList.removeAll(soldFindList);
            if(option.equalsIgnoreCase("tất cả"))
            {
                for(SoldPetDTO petTemp : soldBus.soldList)
                {
                    if( ( valid.normalizeString(petTemp.getName()).toLowerCase().contains(valid.normalizeString(searchText).toLowerCase() ) || 
                        petTemp.getId().toLowerCase().contains(searchText.toLowerCase()) ) )
                    {
                        soldFindList.add(petTemp);
                    }
                }
            }
            
            else 
            {
                String breIDTemp = breed.getID(option);
                for(SoldPetDTO petTemp : soldBus.soldList)
                {
                    if( ( valid.normalizeString(petTemp.getName()).toLowerCase().contains(valid.normalizeString(searchText).toLowerCase()) || 
                            petTemp.getId().equalsIgnoreCase(searchText) ) && 
                            petTemp.getBreedId().equalsIgnoreCase(breIDTemp))
                    {
                        soldFindList.add(petTemp);
                    }
                }
            }
            refreshSoldPetFind(soldFindList);
        }
    }//GEN-LAST:event_tfSearchKeyPressed

    private void btnDateFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDateFilterActionPerformed

    public void revalidateTable()
    {
        Table.removeAll();
        Table.revalidate();
        Table.repaint();
    }
    
    public void refreshPetFindTable(ArrayList<PetOnStoreDTO> list)   
    {
        revalidateTable();
        
        if(list.size() <= 6)
        {
            Table.setLayout(new GridLayout(2, 3, hgap, vgap));
            for(PetOnStoreDTO pet : list)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
            int remains = 6 - list.size();
            for(int i = 0; i < remains; i++)
            {
                EmptyProduct emp = new EmptyProduct();
                Table.add(emp);
            }
        }
        else if(list.size() > 6)
        {
            int rows = 0;
            int remains = list.size() % 3;
            if(remains != 0)
            {
                rows = (list.size() / 3) + 1;
            }
            else{
                rows = (list.size() / 3);
            }
            Table.setLayout(new GridLayout(rows, 3, hgap, vgap));
            
            for(PetOnStoreDTO pet : list)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
        }
    }
    
    public void refreshTable()
    {
        revalidateTable();
        
        
//        POSBus.readData();
//        petOnStoreList = POSBus.petList;
        
        if(POSBus.petList.size() <= 6)
        {
           Table.setLayout(new GridLayout(2, 3, hgap, vgap));
            for(PetOnStoreDTO pet : POSBus.petList)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
            int remains = 6 - POSBus.petList.size();
            for(int i = 0; i < remains; i++)
            {
                EmptyProduct emp = new EmptyProduct();
                Table.add(emp);
            }
        }
        else if(POSBus.petList.size() > 6)
        {
            int rows = 0;
            int remains = POSBus.petList.size() % 3;
            if(remains != 0)
            {
                rows = (POSBus.petList.size() / 3) + 1;
            }
            else{
                rows = (POSBus.petList.size() / 3);
            }
            Table.setLayout(new GridLayout(rows, 3, hgap, vgap));
            
            for(PetOnStoreDTO pet : POSBus.petList)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
        }
        
        Table.revalidate();
        Table.repaint();
    }
    
    public void refreshProductFind(ArrayList<PetProductDTO> list)
    {
        revalidateTable();
        
        if(list.size() <= 6)
        {
            Table.setLayout(new GridLayout(2, 3, hgap, vgap));
            for(PetProductDTO pet : list)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
            int remains = 6 - list.size();
            for(int i = 0; i < remains; i++)
            {
                EmptyProduct emp = new EmptyProduct();
                Table.add(emp);
            }
        }
        else if(list.size() > 6)
        {
            int rows = 0;
            int remains = list.size() % 3;
            if(remains != 0)
            {
                rows = (list.size() / 3) + 1;
            }
            else{
                rows = (list.size() / 3);
            }
            Table.setLayout(new GridLayout(rows, 3, hgap, vgap));
            
            for(PetProductDTO pet : list)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
        }
    }
    
    public void refreshPetProList()
    {
        Table.removeAll();
        Table.revalidate();
        Table.repaint();
        
        
//        PetProBus.readData();
//        proList = PetProBus.productList;
        
//        System.out.println("int 1:"+testList.size());
//        System.out.println("int 2: "+PetProBus.productList.size());
        
        if(PetProBus.productList.size() <= 6)
        {
            Table.setLayout(new GridLayout(2, 3, hgap, vgap));
            for(PetProductDTO product : PetProBus.productList)
            {
                ProductCom productCom = new ProductCom(product, this);
                Table.add(productCom);
            }
            int remains = 6 - PetProBus.productList.size();
            for(int i = 0; i < remains; i++)
            {
                EmptyProduct emp = new EmptyProduct();
                Table.add(emp);
            }
        }
        else if(PetProBus.productList.size() > 6)
        {
            int rows = 0;
            int remains = PetProBus.productList.size() % 3;
            if(remains != 0)
            {
                rows = (PetProBus.productList.size() / 3) + 1;
            }
            else{
                rows = (PetProBus.productList.size() / 3);
            }
            Table.setLayout(new GridLayout(rows, 3, hgap, vgap));
            
            for(PetProductDTO product : PetProBus.productList)
            {
                ProductCom productCom = new ProductCom(product, this);
                Table.add(productCom);
            }
        }
        Table.revalidate();
        Table.repaint();
    }
    
    public void refreshSoldPetFind(ArrayList<SoldPetDTO> list)
    {
        Table.removeAll();
        Table.revalidate();
        Table.repaint();
        
        if(list.size() <= 6)
        {
            Table.setLayout(new GridLayout(2, 3, hgap, vgap));
            for(SoldPetDTO pet : list)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
            int remains = 6 - list.size();
            for(int i = 0; i < remains; i++)
            {
                EmptyProduct emp = new EmptyProduct();
                Table.add(emp);
            }
        }
        else if(list.size() > 6)
        {
            int rows = 0;
            int remains = list.size() % 3;
            if(remains != 0)
            {
                rows = (list.size() / 3) + 1;
            }
            else{
                rows = (list.size() / 3);
            }
            Table.setLayout(new GridLayout(rows, 3, hgap, vgap));
            
            for(SoldPetDTO pet : list)
            {
                ProductCom product = new ProductCom(pet, this);
                Table.add(product);
            }
        }
        Table.revalidate();
        Table.repaint();
    }
    
    public void soldPetTable()
    {
        Table.removeAll();
        Table.revalidate();
        Table.repaint();
        
        
//        soldBus.readData();
//        soldList = soldBus.soldList;
        
        if(soldBus.soldList.size() <= 6)
        {
            Table.setLayout(new GridLayout(2, 3, hgap, vgap));
            for(SoldPetDTO product : soldBus.soldList)
            {
                ProductCom productCom = new ProductCom(product, this);
                Table.add(productCom);
            }
            int remains = 6 - soldBus.soldList.size();
            for(int i = 0; i < remains; i++)
            {
                EmptyProduct emp = new EmptyProduct();
                Table.add(emp);
            }
        }
        else if(soldBus.soldList.size() > 6)
        {
            int rows = 0;
            int remains = soldBus.soldList.size() % 3;
            if(remains != 0)
            {
                rows = (soldBus.soldList.size() / 3) + 1;
            }
            else{
                rows = (soldBus.soldList.size() / 3);
            }
            Table.setLayout(new GridLayout(rows, 3, hgap, vgap));
            
            for(SoldPetDTO product : soldBus.soldList)
            {
                ProductCom productCom = new ProductCom(product, this);
                Table.add(productCom);
            }
        }
        Table.revalidate();
        Table.repaint();
    }
    
    public void loadFilter()
    {
        cbbFilter.removeAllItems();
        cbbFilter.addItem("Tất cả");
        if(section.equals("petonstore") || section.equals("soldpet"))
        {
            for(BreedDTO bre : breed.breedList)
            {
                cbbFilter.addItem(bre.getName());
            }
        }
        else if(section.equals("petproduct"))
        {
            for(PetProductTypeDTO type : typeBus.typeList)
            {
                cbbFilter.addItem(type.getName());
            }
        }
    }
    
    
    
    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.setSize(1280, 620);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductUI product = new ProductUI();
        f.add(product);
        f.setVisible(true);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BaseTable;
    private javax.swing.JPanel NavBar;
    private javax.swing.JPanel Table;
    private javax.swing.JButton btnDateFilter;
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox<String> cbbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbPetOnStore;
    private javax.swing.JLabel lbPetProduct;
    private javax.swing.JLabel lbSoldPet;
    private javax.swing.JScrollPane scrollPane;
    private com.gui.SvgImage svgAdd;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
